version: "3.1"
services:
  api:
    build: ./backend
    image: webdev_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://root:apple1@db/web_dev

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: apple1
      MYSQL_DATABASE: web_dev
      TZ: "US/Eastern"

  frontend:
    build: ./frontend
    image: webdev_frontend
    ports:
      - "80:80"
